import React from 'react';
import {
  View, Text, StyleSheet, ScrollView, TouchableOpacity, Alert, Platform, StatusBar,
} from 'react-native';
import LinearGradient from 'react-native-linear-gradient';
import { useEnergy } from '../context/EnergyContext';
import { formatEnergy, formatCost, formatCO2 } from '../utils/energy';
import Share from 'react-native-share';
import RNFS from 'react-native-fs';
import { format } from 'date-fns';
import { Colors, Typography, Spacing, Radius, Shadows } from '../theme';

const ReportsScreen = () => {
  const { dashboardData, appliances, usageRecords, settings, streak, tips, goals } = useEnergy();

  const generateTextReport = () => {
    const date = format(new Date(), 'MMMM yyyy');
    let r = `ENERGY USAGE REPORT - ${date}\n${'='.repeat(40)}\n\n`;
    if (dashboardData) {
      r += `MONTHLY SUMMARY\nEnergy: ${formatEnergy(dashboardData.totalEnergyConsumed)}\nCost: ${formatCost(dashboardData.totalCost, settings.currency)}\nCO2: ${formatCO2(dashboardData.totalCO2Saved)}\nTrees: ${dashboardData.treesEquivalent.toFixed(1)}\n\n`;
      r += `TOP CONSUMERS\n`;
      dashboardData.topConsumers.slice(0, 3).forEach((c, i) => {
        r += `${i + 1}. ${c.applianceName} - ${formatEnergy(c.monthlyConsumption)}/mo (${c.percentage.toFixed(1)}%)\n`;
      });
      r += `\nCATEGORY BREAKDOWN\n`;
      dashboardData.consumptionByCategory.forEach((category) => {
        r += `- ${category.category}: ${formatEnergy(category.consumption)}/mo | ${formatCost(category.cost, settings.currency)} | ${category.percentage.toFixed(1)}%\n`;
      });
      r += '\n';
    }
    r += `APPLIANCES (${appliances.length})\n`;
    appliances.forEach(a => { r += `- ${a.name} (${a.powerRating}W, ${a.hoursPerDay}h/day)\n`; });
    r += `\nSTREAK: ${streak.currentStreak} days | Best: ${streak.longestStreak}\n`;
    if (goals.length > 0) {
      r += '\nGOAL STATUS\n';
      goals.forEach((goal) => {
        const progress = goal.target > 0 ? (goal.currentValue / goal.target) * 100 : 0;
        r += `- ${goal.type}: ${Math.min(progress, 100).toFixed(0)}% of monthly limit (${goal.isAchieved ? 'within target' : 'above target'})\n`;
      });
    }
    if (tips.length > 0) {
      r += '\nTOP SAVING OPPORTUNITIES\n';
      tips.slice(0, 5).forEach((tip, index) => {
        r += `${index + 1}. ${tip.title} — potential ${formatEnergy(tip.potentialSavings)}/mo\n`;
      });
    }
    r += `\nGenerated by SaveVolt - ${format(new Date(), 'PPpp')}\n`;
    return r;
  };

  const generateCSV = () => {
    let csv = 'Appliance,Category,Power (W),Hours/Day,Daily kWh,Monthly kWh,Monthly Cost\n';
    appliances.forEach(a => {
      const d = (a.powerRating * a.hoursPerDay * a.quantity) / 1000;
      csv += `"${a.name}","${a.category}",${a.powerRating},${a.hoursPerDay},${d.toFixed(2)},${(d * 30).toFixed(2)},${(d * 30 * settings.electricityRate).toFixed(2)}\n`;
    });
    if (dashboardData) {
      csv += '\nCategory,Monthly kWh,Monthly Cost,Share of Energy\n';
      dashboardData.consumptionByCategory.forEach((category) => {
        csv += `"${category.category}",${category.consumption.toFixed(2)},${category.cost.toFixed(2)},${category.percentage.toFixed(2)}%\n`;
      });
    }
    return csv;
  };

  const handleShareText = async () => {
    try { await Share.open({ title: 'Energy Report', message: generateTextReport(), failOnCancel: false }); }
    catch (e) { console.log(e); }
  };

  const handleShareCSV = async () => {
    try {
      const csv = generateCSV();
      const fn = `energy_report_${format(new Date(), 'yyyy-MM-dd')}.csv`;
      const fp = `${RNFS.CachesDirectoryPath}/${fn}`;
      await RNFS.writeFile(fp, csv, 'utf8');
      await Share.open({ title: 'Energy CSV', url: Platform.OS === 'android' ? `file://${fp}` : fp, type: 'text/csv', filename: fn, failOnCancel: false });
    } catch (e) { console.log(e); }
  };

  const handleView = () => Alert.alert('Monthly Report', generateTextReport(), [{ text: 'Close' }], { cancelable: true });

  if (!dashboardData) {
    return (
      <View style={s.emptyWrap}>
        <StatusBar barStyle="dark-content" />
        <Text style={s.emptyIcon}>📄</Text>
        <Text style={s.emptyTitle}>No Report Data</Text>
        <Text style={s.emptyBody}>Add appliances to generate reports</Text>
      </View>
    );
  }

  return (
    <ScrollView style={s.screen} showsVerticalScrollIndicator={false}>
      <StatusBar barStyle="light-content" backgroundColor={Colors.dark} />
      <LinearGradient colors={['#0B1120', '#162032']} style={s.header}>
        <Text style={s.headerLabel}>REPORTS</Text>
        <Text style={s.headerTitle}>Export & Share</Text>
      </LinearGradient>

      <View style={s.body}>
        {/* Summary */}
        <View style={s.summaryCard}>
          <Text style={s.summaryDate}>{format(new Date(), 'MMMM yyyy')}</Text>
          <View style={s.summaryRow}>
            {[
              { l: 'Energy', v: formatEnergy(dashboardData.totalEnergyConsumed) },
              { l: 'Cost', v: formatCost(dashboardData.totalCost, settings.currency) },
              { l: 'CO₂', v: formatCO2(dashboardData.totalCO2Saved) },
            ].map(m => (
              <View key={m.l} style={s.summaryItem}>
                <Text style={s.summaryVal}>{m.v}</Text>
                <Text style={s.summaryLbl}>{m.l}</Text>
              </View>
            ))}
          </View>
        </View>

        <View style={s.coverageCard}>
          <Text style={s.coverageTitle}>Included in this report</Text>
          <Text style={s.coverageText}>Monthly totals, top consumers, category breakdown, tracked appliances, goal status, streaks, and up to five saving opportunities.</Text>
        </View>

        {/* Export buttons */}
        <Text style={s.secTitle}>Export Options</Text>
        {[
          { icon: '📄', title: 'View Full Report', desc: 'Detailed monthly summary', fn: handleView },
          { icon: '📱', title: 'Share Text Report', desc: 'Via message, email, social', fn: handleShareText },
          { icon: '📊', title: 'Export CSV', desc: 'Spreadsheet-ready data', fn: handleShareCSV },
        ].map(b => (
          <TouchableOpacity key={b.title} style={s.exportBtn} onPress={b.fn} activeOpacity={0.7}>
            <Text style={s.exportIcon}>{b.icon}</Text>
            <View style={s.exportInfo}>
              <Text style={s.exportTitle}>{b.title}</Text>
              <Text style={s.exportDesc}>{b.desc}</Text>
            </View>
            <Text style={s.arrow}>›</Text>
          </TouchableOpacity>
        ))}

        {/* Recent activity */}
        {usageRecords.length > 0 && (
          <View style={s.recentActivity}>
            <Text style={s.secTitle}>Recent Activity</Text>
            {usageRecords.slice(-5).reverse().map(r => (
              <View key={r.id} style={s.recordRow}>
                <Text style={s.recordDate}>{format(new Date(r.date), 'MMM dd, yyyy')}</Text>
                <View style={s.recordStats}>
                  <Text style={s.recordStat}>{formatEnergy(r.totalConsumption)}</Text>
                  <Text style={s.recordStat}>{formatCost(r.totalCost, settings.currency)}</Text>
                </View>
              </View>
            ))}
          </View>
        )}
      </View>
    </ScrollView>
  );
};

const s = StyleSheet.create({
  screen: { flex: 1, backgroundColor: Colors.background },
  emptyWrap: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: Colors.background, padding: 40 },
  emptyIcon: { fontSize: 56, marginBottom: 16 },
  emptyTitle: { ...Typography.h1, color: Colors.text, marginBottom: 8 },
  emptyBody: { ...Typography.bodyMedium, color: Colors.textSecondary, textAlign: 'center' },
  header: { paddingTop: 54, paddingBottom: 28, paddingHorizontal: Spacing.page, alignItems: 'center' },
  headerLabel: { ...Typography.overline, color: Colors.primary, marginBottom: 4 },
  headerTitle: { ...Typography.displaySmall, color: '#fff' },
  body: { padding: Spacing.page },
  summaryCard: { backgroundColor: Colors.card, borderRadius: Radius.card, padding: Spacing.xl, ...Shadows.md, marginBottom: 20 },
  summaryDate: { ...Typography.label, color: Colors.textSecondary, textAlign: 'center', marginBottom: 14 },
  summaryRow: { flexDirection: 'row', justifyContent: 'space-around' },
  summaryItem: { alignItems: 'center' },
  summaryVal: { ...Typography.stat, color: Colors.primary },
  summaryLbl: { ...Typography.labelSmall, color: Colors.textMuted, marginTop: 4 },
  coverageCard: { backgroundColor: Colors.primarySoft, borderRadius: Radius.md, padding: 14, marginBottom: 20 },
  coverageTitle: { ...Typography.label, color: Colors.primaryDark, marginBottom: 4 },
  coverageText: { ...Typography.bodySmall, color: Colors.textSecondary, lineHeight: 18 },
  secTitle: { ...Typography.label, color: Colors.textSecondary, marginBottom: 10, letterSpacing: 0.5 },
  exportBtn: { flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.card, borderRadius: Radius.card, padding: 16, marginBottom: 10, ...Shadows.sm },
  exportIcon: { fontSize: 32, marginRight: 14 },
  exportInfo: { flex: 1 },
  exportTitle: { ...Typography.h3, color: Colors.text },
  exportDesc: { ...Typography.bodySmall, color: Colors.textMuted, marginTop: 1 },
  arrow: { fontSize: 22, color: Colors.textMuted },
  recentActivity: { marginTop: 24, marginBottom: 30 },
  recordRow: { backgroundColor: Colors.card, borderRadius: Radius.sm, padding: 12, marginBottom: 6, ...Shadows.sm },
  recordDate: { ...Typography.label, color: Colors.text, marginBottom: 6 },
  recordStats: { flexDirection: 'row', justifyContent: 'space-around' },
  recordStat: { ...Typography.bodyMedium, color: Colors.textSecondary },
});

export default ReportsScreen;
