import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  Alert,
} from 'react-native';
import { useEnergy } from '../context/EnergyContext';
import { formatEnergy, formatCost, formatCO2 } from '../utils/energy';
import Share from 'react-native-share';
import { format } from 'date-fns';

const ReportsScreen = () => {
  const { dashboardData, appliances, usageRecords, tips, settings, streak } = useEnergy();

  const generateTextReport = () => {
    const date = format(new Date(), 'MMMM yyyy');
    
    let report = `📊 ENERGY USAGE REPORT - ${date}\n`;
    report += `${'='.repeat(50)}\n\n`;

    if (dashboardData) {
      report += `📈 MONTHLY SUMMARY\n`;
      report += `${'-'.repeat(50)}\n`;
      report += `⚡ Total Energy: ${formatEnergy(dashboardData.totalEnergyConsumed)}\n`;
      report += `💰 Total Cost: ${formatCost(dashboardData.totalCost, settings.currency)}\n`;
      report += `🌍 CO₂ Emissions: ${formatCO2(dashboardData.totalCO2Saved)}\n`;
      report += `🌳 Tree Equivalent: ${dashboardData.treesEquivalent.toFixed(1)} trees\n\n`;

      report += `🔥 TOP 3 CONSUMERS\n`;
      report += `${'-'.repeat(50)}\n`;
      dashboardData.topConsumers.slice(0, 3).forEach((consumer, index) => {
        report += `${index + 1}. ${consumer.applianceName}\n`;
        report += `   Energy: ${formatEnergy(consumer.monthlyConsumption)}/month\n`;
        report += `   Cost: ${formatCost(consumer.monthlyCost, settings.currency)}/month\n`;
        report += `   Percentage: ${consumer.percentage.toFixed(1)}%\n\n`;
      });

      report += `📊 CONSUMPTION BY CATEGORY\n`;
      report += `${'-'.repeat(50)}\n`;
      dashboardData.consumptionByCategory.forEach((category) => {
        report += `${category.category}: ${formatEnergy(category.consumption)} (${category.percentage.toFixed(1)}%)\n`;
      });
      report += `\n`;
    }

    report += `📱 YOUR APPLIANCES (${appliances.length})\n`;
    report += `${'-'.repeat(50)}\n`;
    appliances.forEach((appliance) => {
      report += `• ${appliance.name} (${appliance.category})\n`;
      report += `  Power: ${appliance.powerRating}W | Usage: ${appliance.hoursPerDay}h/day\n`;
    });
    report += `\n`;

    report += `🏆 YOUR PROGRESS\n`;
    report += `${'-'.repeat(50)}\n`;
    report += `🔥 Current Streak: ${streak.currentStreak} days\n`;
    report += `📅 Total Active Days: ${streak.totalDaysActive}\n`;
    report += `🎯 Longest Streak: ${streak.longestStreak} days\n\n`;

    report += `💡 TOP ENERGY-SAVING TIPS\n`;
    report += `${'-'.repeat(50)}\n`;
    tips.slice(0, 5).forEach((tip, index) => {
      report += `${index + 1}. ${tip.title}\n`;
      report += `   ${tip.description}\n`;
      report += `   💰 Potential savings: ${formatEnergy(tip.potentialSavings)}/month\n\n`;
    });

    report += `${'-'.repeat(50)}\n`;
    report += `Generated by Energy Tracker App\n`;
    report += `${format(new Date(), 'PPpp')}\n`;

    return report;
  };

  const generateCSV = () => {
    let csv = 'Appliance,Category,Power (W),Hours/Day,Daily Consumption (kWh),Monthly Consumption (kWh),Monthly Cost\n';
    
    appliances.forEach((appliance) => {
      const dailyKWh = (appliance.powerRating * appliance.hoursPerDay * appliance.quantity) / 1000;
      const monthlyKWh = dailyKWh * 30;
      const monthlyCost = monthlyKWh * settings.electricityRate;
      
      csv += `"${appliance.name}","${appliance.category}",${appliance.powerRating},${appliance.hoursPerDay},${dailyKWh.toFixed(2)},${monthlyKWh.toFixed(2)},${monthlyCost.toFixed(2)}\n`;
    });

    return csv;
  };

  const handleShareText = async () => {
    try {
      const report = generateTextReport();
      await Share.open({
        title: 'Energy Usage Report',
        message: report,
        failOnCancel: false,
      });
    } catch (error) {
      console.log('Share error:', error);
    }
  };

  const handleShareCSV = async () => {
    try {
      const csv = generateCSV();
      await Share.open({
        title: 'Energy Data CSV',
        message: csv,
        failOnCancel: false,
      });
    } catch (error) {
      console.log('Share error:', error);
    }
  };

  const handleViewReport = () => {
    const report = generateTextReport();
    Alert.alert('Monthly Report', report, [{ text: 'Close' }], { cancelable: true });
  };

  if (!dashboardData) {
    return (
      <View style={styles.emptyContainer}>
        <Text style={styles.emptyIcon}>📄</Text>
        <Text style={styles.emptyTitle}>No Report Data</Text>
        <Text style={styles.emptyText}>
          Add appliances and track usage to generate reports
        </Text>
      </View>
    );
  }

  return (
    <ScrollView style={styles.container}>
      <View style={styles.header}>
        <Text style={styles.title}>📄 Reports & Export</Text>
        <Text style={styles.subtitle}>Share your energy insights</Text>
      </View>

      <View style={styles.content}>
        {/* Summary Card */}
        <View style={styles.summaryCard}>
          <Text style={styles.summaryTitle}>📊 Monthly Summary</Text>
          <Text style={styles.summaryDate}>{format(new Date(), 'MMMM yyyy')}</Text>
          
          <View style={styles.summaryStats}>
            <View style={styles.summaryStat}>
              <Text style={styles.summaryStatLabel}>Total Energy</Text>
              <Text style={styles.summaryStatValue}>
                {formatEnergy(dashboardData.totalEnergyConsumed)}
              </Text>
            </View>
            <View style={styles.summaryStat}>
              <Text style={styles.summaryStatLabel}>Total Cost</Text>
              <Text style={styles.summaryStatValue}>
                {formatCost(dashboardData.totalCost, settings.currency)}
              </Text>
            </View>
            <View style={styles.summaryStat}>
              <Text style={styles.summaryStatLabel}>CO₂ Emissions</Text>
              <Text style={styles.summaryStatValue}>
                {formatCO2(dashboardData.totalCO2Saved)}
              </Text>
            </View>
          </View>
        </View>

        {/* Export Options */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>📤 Export Options</Text>

          <TouchableOpacity style={styles.exportButton} onPress={handleViewReport}>
            <View style={styles.exportButtonContent}>
              <Text style={styles.exportIcon}>📄</Text>
              <View style={styles.exportInfo}>
                <Text style={styles.exportTitle}>View Full Report</Text>
                <Text style={styles.exportDescription}>
                  See detailed monthly summary
                </Text>
              </View>
            </View>
          </TouchableOpacity>

          <TouchableOpacity style={styles.exportButton} onPress={handleShareText}>
            <View style={styles.exportButtonContent}>
              <Text style={styles.exportIcon}>📱</Text>
              <View style={styles.exportInfo}>
                <Text style={styles.exportTitle}>Share Text Report</Text>
                <Text style={styles.exportDescription}>
                  Share via message, email, or social media
                </Text>
              </View>
            </View>
          </TouchableOpacity>

          <TouchableOpacity style={styles.exportButton} onPress={handleShareCSV}>
            <View style={styles.exportButtonContent}>
              <Text style={styles.exportIcon}>📊</Text>
              <View style={styles.exportInfo}>
                <Text style={styles.exportTitle}>Export CSV Data</Text>
                <Text style={styles.exportDescription}>
                  Download appliance data as CSV
                </Text>
              </View>
            </View>
          </TouchableOpacity>
        </View>

        {/* Report Preview */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>👀 Report Preview</Text>
          <View style={styles.previewCard}>
            <Text style={styles.previewTitle}>What's Included:</Text>
            <Text style={styles.previewItem}>✓ Monthly energy consumption summary</Text>
            <Text style={styles.previewItem}>✓ Cost breakdown by appliance</Text>
            <Text style={styles.previewItem}>✓ Environmental impact (CO₂, trees)</Text>
            <Text style={styles.previewItem}>✓ Top energy consumers</Text>
            <Text style={styles.previewItem}>✓ Category-wise consumption</Text>
            <Text style={styles.previewItem}>✓ Progress & streak information</Text>
            <Text style={styles.previewItem}>✓ Personalized energy-saving tips</Text>
          </View>
        </View>

        {/* Usage History */}
        {usageRecords.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>📅 Recent Activity</Text>
            {usageRecords.slice(-5).reverse().map((record) => (
              <View key={record.id} style={styles.recordCard}>
                <Text style={styles.recordDate}>
                  {format(new Date(record.date), 'MMM dd, yyyy')}
                </Text>
                <View style={styles.recordStats}>
                  <Text style={styles.recordStat}>
                    ⚡ {formatEnergy(record.totalConsumption)}
                  </Text>
                  <Text style={styles.recordStat}>
                    💰 {formatCost(record.totalCost, settings.currency)}
                  </Text>
                </View>
              </View>
            ))}
          </View>
        )}
      </View>
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 40,
    backgroundColor: '#f5f5f5',
  },
  emptyIcon: {
    fontSize: 80,
    marginBottom: 20,
  },
  emptyTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 10,
  },
  emptyText: {
    fontSize: 16,
    color: '#666',
    textAlign: 'center',
  },
  header: {
    padding: 20,
    backgroundColor: '#3F51B5',
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 16,
    color: '#fff',
    opacity: 0.9,
  },
  content: {
    padding: 15,
  },
  summaryCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 20,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  summaryTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 5,
  },
  summaryDate: {
    fontSize: 14,
    color: '#666',
    marginBottom: 15,
  },
  summaryStats: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  summaryStat: {
    alignItems: 'center',
  },
  summaryStatLabel: {
    fontSize: 12,
    color: '#666',
    marginBottom: 5,
  },
  summaryStatValue: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#3F51B5',
  },
  section: {
    marginBottom: 25,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 15,
  },
  exportButton: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 15,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  exportButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  exportIcon: {
    fontSize: 40,
    marginRight: 15,
  },
  exportInfo: {
    flex: 1,
  },
  exportTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 4,
  },
  exportDescription: {
    fontSize: 13,
    color: '#666',
  },
  previewCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  previewTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 12,
  },
  previewItem: {
    fontSize: 14,
    color: '#666',
    marginBottom: 8,
    paddingLeft: 10,
  },
  recordCard: {
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 1,
    elevation: 1,
  },
  recordDate: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
    marginBottom: 8,
  },
  recordStats: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  recordStat: {
    fontSize: 13,
    color: '#666',
  },
});

export default ReportsScreen;
